apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-edu-goods-configmap
  namespace: edu-goods
data:
  application.yml: |
    app:
      run:
        type: goods
    goods:
      service:
        url: http://edu-goods.edu-goods-ns.svc.cluster.local