apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-edu-user-configmap
  namespace: edu-user
data:
  application.yml: |
    app:
      run:
        type: user
    goods:
      service:
        url: http://edu-goods.edu-goods-ns.svc.cluster.local